replicaCount: 1

image:
  repository: quay.io/ecosystem-appeng/h2o-knowledge-mgmt-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources: {}

aws-compatible-storage:
  enabled: true
  fullnameOverride: h2o-knowledge-mgmt-storage
  s3:
    region: us-east-1
    accessKeyId: ""
    secretAccessKey: ""
  auth:
    enabled: false
  route:
    enabled: false
    s3Api:
      enabled: false
  storage:
    data:
      size: 10Gi

sampleFileUpload:
  enabled: true
  bucket: documents
  region: us-east-1
  image:
    repository: quay.io/ecosystem-appeng/h2o-knowledge-mgmt-document-uploader-job
    tag: "0.1.4"
    pullPolicy: IfNotPresent
  urls:
    - https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/pdf/overview/OpenShift_Container_Platform-4.19-Overview-en-US.pdf
